/**
 * Main entrypoint into SLO/R entity functionality.
 *
 * @file This files defines the core nr1-slo-r nerdlet class.
 * @author Gil Rice
 */
/** core */
import React from 'react';
/** nr1 */
import { NerdletStateContext } from 'nr1';
/** local */
import SLOREntityNerdlet from '../slo-r-entity';
/** 3rd party */

/**
 * Code class generated by New Relic One CLI.
 */
export default class Nr1CsgSloR extends React.Component {
  render() {
    return (
      <NerdletStateContext.Consumer>
        {nerdletUrlState => (
          <SLOREntityNerdlet nerdletUrlState={nerdletUrlState} />
        )}
      </NerdletStateContext.Consumer>
    );
  } // render
} // Nr1CsgSloR
